apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "detection-api.fullname" . }}
  labels:
    {{- include "detection-api.labels" . | nindent 4 }}
spec:
  minAvailable: 2
  selector:
    matchLabels:
      {{- include "detection-api.selectorLabels" . | nindent 6 }}
  unhealthyPodEvictionPolicy: AlwaysAllow
